print("")
print("Exercício - Operações Numéricas \n")

num1 = int(input("Digite um número: "))
num2 = int(input("Digite outro número: "))
soma = num1 + num2
subtracao = num1 - num2
multiplicacao = (num1 * num2)
divisao = (num1 / num2)
fracao = (num1 // num2)
restoD = (num1 % num2)
potencia = (num1 ** num2)

print("")
print('O resultado da soma entre {} e {} é igual a: {}'.format(num1, num2, soma))
print("")
print('O resultado da subtração entre {} e {} é igual a: {}'.format(num1, num2, subtracao))
print("")
print('O resultado da multiplicação entre {} e {} é igual a: {}'.format(num1, num2, multiplicacao))
print("")
print('O resultado da divisão entre {} e {} é igual a: {}'.format(num1, num2, divisao))
print("")
print('O resultado da fração entre {} e {} é igual a: {}'.format(num1, num2, fracao))
print("")
print('O resto da divisão entre {} e {} é igual a: {}'.format(num1, num2, restoD))
print("")
print('O resultado da potênciação entre {} e {} é igual a: {}'.format(num1, num2, potencia))
print("")
print("Fim do programa")
